export const VIDEOS_KEYS = {
	HOME_VIDEOS: 'VIDEOS_HOME',
}

export const CHANNELS_KEYS = {
	VIDEO_CARD_AVATAR: 'CHANNEL_VIDEO_CARD_AVATAR',
	CHANNEL_INFO: 'CHANNEL_INFO',
	CHANNEL_SECTION: 'CHANNEL_SECTION',
	CHANNEL_SECTION_PLAYLISTS: 'CHANNEL_SECTION_PLAYLISTS',
	CHANNEL_SECTION_PLAYLISTITEMS: 'CHANNEL_SECTION_PLAYLISTITEMS',
}
